In [1]:
# Imports

import torch

In [17]:
#构造一个5*3矩阵，不初始化
x = torch.empty(5, 3)
print(x)

#构造一个5*3矩阵，随机初始化矩阵
x = torch.rand(5, 3) #返回一个张量，包含了从区间[0, 1)的均匀分布中抽取的一组随机数
print(x)

x = torch.randn(5, 3) #返回一个张量，包含了从标准正态分布（均值为0，方差为1，即高斯白噪声）中抽取的一组随机数
print(x)

#构造一个矩阵全为0，而且数据类型是long
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

#直接使用数据构造一个张量
x = torch.tensor([5.5, 3])
print(x)

#创建一个tensor基于已经存在的tensor
x = x.new_ones(5, 3, dtype=torch.double)      
# new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    
# override dtype!
print(x)                                      
# result has the same size

print(x.size()) #获取维度信息

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 9.3607e-43, 0.0000e+00],
        [0.0000e+00, 5.5572e-01, 0.0000e+00]])
tensor([[0.6347, 0.7872, 0.5380],
        [0.8266, 0.3181, 0.9531],
        [0.3864, 0.0694, 0.7308],
        [0.4605, 0.1534, 0.2910],
        [0.9251, 0.4580, 0.9595]])
tensor([[-0.0446,  0.0483, -0.2489],
        [-0.7796,  1.8542,  0.5033],
        [-1.6185,  0.6642,  0.8451],
        [-0.2817,  1.6861, -0.1320],
        [-0.4188, -0.7152, -0.4451]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.0447, -0.5649, -0.0825],
        [ 0.9448, -0.7180,  0.1949],
        [-0.2352,  1.5759,  0.7241],
        [ 1.2947,  0.1221,  0.3083],
        [-0

In [15]:
#加法
y = torch.rand(5, 3)
print(x + y)

print(torch.add(x, y)) #这种直观一些

y.add_(x)
print(y)
#note: 任何使张量会发生变化的操作都有一个后缀“_”.
#例如：x.copy_(y), x.t_(),将会改变x

#提供一个输出tensor作为参数
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.0881,  0.1031, -0.1286],
        [-0.7086,  0.2330,  0.8476],
        [ 2.9540,  0.1087,  1.6039],
        [ 0.4912,  0.5128,  1.8104],
        [-0.5175,  0.5557,  0.0847]])
tensor([[-0.0881,  0.1031, -0.1286],
        [-0.7086,  0.2330,  0.8476],
        [ 2.9540,  0.1087,  1.6039],
        [ 0.4912,  0.5128,  1.8104],
        [-0.5175,  0.5557,  0.0847]])
tensor([[-0.0881,  0.1031, -0.1286],
        [-0.7086,  0.2330,  0.8476],
        [ 2.9540,  0.1087,  1.6039],
        [ 0.4912,  0.5128,  1.8104],
        [-0.5175,  0.5557,  0.0847]])
tensor([[-0.4496, -0.0398, -0.6460],
        [-2.0239,  0.0243,  1.0459],
        [ 5.0854, -0.0446,  2.3499],
        [ 0.2018,  0.7042,  3.4476],
        [-1.3822,  0.7846, -0.8107]])


In [16]:
#索引操作
print(x[:, 1]) #所有行的第1列

tensor([-0.1429, -0.2087, -0.1533,  0.1914,  0.2289])


In [18]:
#改变tensor大小或形状
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) #the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [20]:
#获取值
x = torch.randn(1) #只有一个元素的tensor
print(x)
print(x.item())

tensor([1.3768])
1.3767856359481812
